Addtional features
CKRP-FM/backronym-gen pull request #40
Opened 2022-08-28 18:31 UTC by keonp

- Created API loading screen, runs on each API search and when loading profile page
- Runtime is 500ms on API calls and 800ms on profile load, both can be changed with the timeout function created
- Loading screen container is 260px x 260px
- Resolves profile refresh issue as content is fully loaded by the time the loading screen is done
- Ability to save words by enter button is included via having the Save Word button being auto-focused when it appears each time

2022-08-28 20:45 UTC, chxwcodes commented on src/App.css
> +.loadingBar {
hurray for fancy loading screens 🤩

2022-08-28 20:47 UTC, chxwcodes approved these changes
so many QoL changes 😍

2022-08-28 23:05 UTC, pinggyu approved these changes

2022-08-28 23:05 UTC, pinggyu commented on src/App.css
> +  font-family: "Montserrat", sans-serif;
replace with the sass variable $bodyFont for consistency

2022-08-28 23:07 UTC, pinggyu requested changes

2022-08-28 23:07 UTC, pinggyu commented on src/components/UserProfile.js
> +                                        <li className="galleryCard" key={result.key}>
I believe a large portion of the code is wrapped inside the GalleryCard component right now to avoid repetitive code with the gallery

2022-08-28 23:08 UTC, pinggyu commented on src/components/UserProfile.js
> +                                        <li className="galleryCard" key={result.key}>
This is probably what's causing the conflict :(

2022-08-29 18:22 UTC, pinggyu approved these changes

2022-08-29 18:22 UTC, Uncle-Shred approved these changes

2022-08-29 18:22 UTC, merged

2022-08-29 18:22 UTC, keonp commented
uh oh